### PR TITLE
Patch with Rpath rather than runpath, to give precedence to patched location over LD_LIBRARY_PATH

### PR DESCRIPTION
**Pull request by danpetry**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by danpetry** [comment]
@conda-forge-admin, please rerender

**Comment by danpetry** [comment]
@conda-forge-admin, please rerender

**Review by vyasr — APPROVED** [review]

**Comment by vyasr** [comment]
Thanks, looks like I missed one in https://github.com/conda-forge/cuda-cudart-feedstock/issues/21!

**Review by bdice — APPROVED** [review]

**Comment by bdice** [comment]
I merged #9 first, and bumped the build number again. This is good to go when CI passes.

**Comment by jakirkham** [comment]
CI was failing due to issue: https://github.com/conda-forge/status/issues/177

So dropped automerge for the moment

Tried to push a test as well loosely based on a script we have used elsewhere. It may need tweaks though

**Comment by danpetry** [comment]
Thanks for the reviews and the added tests.

**Comment by danpetry** [comment]
Is this ready to go or does it need more changes? (aside from sorting out merge conflicts)

**Comment by bdice** [comment]
I fixed conflicts and will enable automerge.

**Comment by jakirkham** [comment]
Thanks all! 🙏

**Pull request merged**
